services:
  - type: web
    name: keep-notatki-sqlite
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app_sqlite.py"
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
